import { ChevronDown, CircleHelp, Menu, Search, ShoppingBag, UserRound, X } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Link, NavLink, useNavigate } from 'react-router-dom'
import { useCart } from '../../context/CartContext'
import { useAuth } from '../../context/AuthContext'

const petMenu = { Cats:['Food','Treats','Toys','Grooming','Health'], Dogs:['Food','Treats','Toys','Walking','Grooming','Health'], Birds:['Food','Treats','Toys','Cage Accessories','Health'] }
const nav = ['Cats','Dogs','Birds','Food & Treats','Health & Care','Toys & Accessories','Offers']
const adminLinkClass = 'my-1 flex items-center rounded border border-rose-200 bg-rose-50 px-4 py-2 text-sm font-bold text-red-950 shadow-sm transition hover:bg-rose-100'
const adminMobileClass = 'mx-1 my-2 block rounded border border-rose-200 bg-rose-50 px-3 py-3 font-bold text-red-950 hover:bg-rose-100'
const adminBadgeClass = 'ml-2 rounded bg-rose-200 px-1.5 py-0.5 text-[10px] uppercase tracking-wide text-red-950'

export function Header() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [search, setSearch] = useState('')
  const navigate = useNavigate()
  const { count, total, setIsOpen } = useCart()
  const { session, backendAccount } = useAuth()
  const isStaff = backendAccount?.role?.toLowerCase() === 'staff'
  const accountPath = session ? '/account' : '/login'
  const submit = (event: FormEvent) => { event.preventDefault(); navigate(`/shop?q=${encodeURIComponent(search)}`); setMobileOpen(false) }

  return <header className="relative z-40">
    <div className="hidden bg-brand py-1.5 text-[11px] font-medium tracking-wide text-white md:block"><div className="container-page grid grid-cols-3"><span>UK premium pet product supplier</span><span className="text-center">Helpful pet care guides</span><span className="text-right">Free delivery over £45</span></div></div>
    <div className="border-b border-line bg-white"><div className="container-page flex h-16 items-center gap-3 lg:h-20 lg:gap-8"><button onClick={() => setMobileOpen(true)} className="p-2 lg:hidden" aria-label="Open navigation"><Menu /></button><Link to="/" aria-label="My Pet Food home" className="flex shrink-0 items-center"><img src="/brand/mypetfood-logo.jpeg" alt="My Pet Food Pet Supplies" className="h-auto w-36 sm:w-44 lg:w-52" /></Link><form onSubmit={submit} className="relative hidden max-w-2xl flex-1 md:block"><label className="sr-only" htmlFor="header-search">Search products</label><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" size={19}/><input id="header-search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search products, brands or pets..." className="w-full border border-line bg-sand/40 py-3 pl-10 pr-3 text-sm outline-none transition focus:border-brand"/></form><div className="ml-auto flex items-center gap-1 sm:gap-3"><Link to={accountPath} aria-label={session ? 'Account' : 'Sign in'} className="hidden p-2 hover:text-brand sm:block"><UserRound size={21}/></Link><button aria-label="Help" className="hidden p-2 hover:text-brand sm:block"><CircleHelp size={21}/></button><button onClick={() => setIsOpen(true)} className="flex items-center gap-2 p-2 hover:text-brand" aria-label="Open basket"><span className="relative"><ShoppingBag size={22}/>{count > 0 && <span className="absolute -right-2 -top-2 grid h-4 w-4 place-items-center rounded-full bg-accent text-[9px] font-bold text-white">{count}</span>}</span><span className="hidden text-left text-xs lg:block"><b className="block">Basket</b>£{total.toFixed(2)}</span></button></div></div><form onSubmit={submit} className="border-t border-line p-3 md:hidden"><div className="container-page relative"><Search className="absolute left-7 top-1/2 -translate-y-1/2 text-gray-500" size={18}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search products..." className="w-full border border-line bg-sand/40 py-2.5 pl-10 pr-3 text-sm outline-none"/></div></form></div>
    <nav className="hidden border-b border-line bg-white lg:block"><div className="container-page flex items-stretch justify-center"><Link className="px-4 py-3 text-sm font-bold hover:text-brand" to="/shop">Shop all</Link>{nav.map(item => <div className="group relative" key={item}>{['Cats','Dogs','Birds'].includes(item) ? <><NavLink to={`/category/${item.toLowerCase()}`} className="flex items-center gap-1 px-4 py-3 text-sm font-bold hover:text-brand">{item}<ChevronDown size={15}/></NavLink><div className="invisible absolute left-0 top-full w-44 border border-line bg-white p-2 opacity-0 shadow-card transition group-hover:visible group-hover:opacity-100">{petMenu[item as keyof typeof petMenu].map(sub => <Link key={sub} to={`/shop?pet=${item}&category=${encodeURIComponent(sub)}`} className="block px-3 py-2 text-sm hover:bg-sand hover:text-brand">{sub}</Link>)}</div></> : <Link to={item === 'Offers' ? '/shop?offer=true' : '/shop'} className="block px-4 py-3 text-sm font-bold hover:text-brand">{item}</Link>}</div>)}{isStaff && <Link className={adminLinkClass} to="/account">Admin tools <span className={adminBadgeClass}>Admin</span></Link>}</div></nav>
    <div className={`fixed inset-0 z-50 lg:hidden ${mobileOpen ? 'pointer-events-auto' : 'pointer-events-none'}`}><div onClick={() => setMobileOpen(false)} className={`absolute inset-0 bg-ink/40 transition ${mobileOpen ? 'opacity-100' : 'opacity-0'}`}/><div className={`relative h-full w-80 max-w-[85%] bg-white p-5 transition-transform ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="mb-7 flex items-center justify-between"><b className="text-brand">My Pet Food</b><button onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X/></button></div><Link to={accountPath} onClick={() => setMobileOpen(false)} className="block border-b border-line py-3 font-bold">{session ? 'My account' : 'Sign in'}</Link>{isStaff && <Link to="/account" onClick={() => setMobileOpen(false)} className={adminMobileClass}>Admin tools <span className={adminBadgeClass}>Admin</span></Link>}<Link to="/shop" onClick={() => setMobileOpen(false)} className="block border-b border-line py-3 font-bold">Shop all products</Link>{nav.map(item => <Link key={item} to={['Cats','Dogs','Birds'].includes(item) ? `/category/${item.toLowerCase()}` : '/shop'} onClick={() => setMobileOpen(false)} className="block border-b border-line py-3 font-bold">{item}</Link>)}</div></div>
  </header>
}
