import { ArrowRight, Search } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ProductGrid } from '../components/shop/ProductGrid'
import { useCatalog } from '../context/CatalogContext'

const photo = (id:string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1100&q=85`
const petCards=[{name:'Cats',copy:'Food, toys and cosy comforts for curious cats.',image:photo('photo-1514888286974-6c03e2ca1dba')},{name:'Dogs',copy:'Trusted everyday essentials for dogs of all sizes.',image:photo('photo-1558788353-f76d92427f16')},{name:'Birds',copy:'Brighten their day with food, toys and care.',image:photo('photo-1444464666168-49d633b86797')}]
export function HomePage(){const [query,setQuery]=useState('');const {products,loading,error}=useCatalog();const navigate=useNavigate(); const search=(e:FormEvent)=>{e.preventDefault();navigate(`/shop?q=${encodeURIComponent(query)}`)};return <>
<main>
<section className="bg-sand"><div className="container-page grid items-stretch lg:grid-cols-5"><div className="flex flex-col justify-center py-14 lg:col-span-2 lg:py-20"><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-accent">Everything they need</p><h1 className="max-w-md text-4xl font-bold leading-tight tracking-tight sm:text-5xl">Happy pets start here</h1><p className="mt-5 max-w-md text-base leading-7 text-gray-700">Quality food, treats, toys and everyday essentials for cats, dogs and birds.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/shop" className="btn-primary">Shop all products <ArrowRight size={17}/></Link><a href="#pet-categories" className="btn-secondary">Explore categories</a></div></div><div className="relative min-h-[300px] overflow-hidden lg:col-span-3 lg:min-h-[480px]"><img src={photo('photo-1601758228041-f3b2795255f1')} alt="A happy dog relaxing at home" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute bottom-5 left-5 bg-white/95 px-4 py-3 text-sm shadow-card"><b className="block text-brand">Selected with care</b><span className="text-xs text-gray-600">For every feather, whisker & wag</span></div></div></div></section>
<section id="pet-categories" className="container-page py-14 sm:py-20"><div className="mb-8 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-accent">A little something for everyone</p><h2 className="section-title mt-2">Shop by pet</h2></div><Link to="/shop" className="hidden text-sm font-bold text-brand underline sm:block">View all products</Link></div><div className="grid gap-5 md:grid-cols-3">{petCards.map(card=><article key={card.name} className="group relative min-h-[320px] overflow-hidden bg-ink"><img src={card.image} alt={card.name} className="absolute inset-0 h-full w-full object-cover opacity-80 transition duration-500 group-hover:scale-105"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 to-transparent p-6 text-white"><h3 className="text-2xl font-bold">{card.name}</h3><p className="mt-1 max-w-xs text-sm text-white/85">{card.copy}</p><Link to={`/category/${card.name.toLowerCase()}`} className="mt-4 inline-flex items-center gap-1 text-sm font-bold underline underline-offset-4">Shop now <ArrowRight size={15}/></Link></div></article>)}</div></section>
<section className="bg-brand py-11 text-white"><div className="container-page grid items-center gap-6 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-200">Search our range</p><h2 className="mt-2 text-2xl font-bold">Find exactly what they need</h2><p className="mt-2 text-sm text-white/80">Search our range of food, health products, treats and accessories.</p></div><form onSubmit={search} className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-white py-3.5 pl-11 pr-28 text-sm text-ink outline-none ring-accent focus:ring-2" placeholder="Try 'dog food' or 'cat toys'"/><button className="absolute right-1.5 top-1.5 bg-accent px-4 py-2.5 text-sm font-bold">Search</button></form></div></section>
<section className="container-page py-14 sm:py-20"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-accent">Customer favourites</p><h2 className="section-title mt-2">Popular products</h2></div>{loading?<p className="border border-line p-10 text-center text-gray-600">Loading products…</p>:error?<p role="alert" className="border border-red-200 bg-red-50 p-10 text-center text-sm text-red-800">{error}</p>:<ProductGrid products={products.filter(p=>p.featured).slice(0,8)}/>}<div className="mt-9 text-center"><Link to="/shop" className="btn-secondary">View all products</Link></div></section>
</main></>}
